### ISSUE TITLE
submission type for project 1

### ISSUE THREAD

**Issue by shihwachang** [ccsf-math-108/materials-fa23#13]
In the instruction, it said submit HTML format, yet Canvas would only accept IPYNB file. I have submit it in IPYNB file successfully, no big deal, but just a small fix is required.

**Comment by shawnwiggins** [comment]
Thank you for posting this, @shihwachang. 

This is not an issue. There are two assignments in Canvas for Project 1. One is the main assignment page (Project 1: World Progress) where you submit the IPYNB file at the end. The other is the checkpoint assignment (Project 1: World Progress (Checkpoint)) that will be open next week for the lab assignment where you submit the HTML file showing your progress.

_I'll leave this open until the checkpoint deadline for others to reference._
