### ISSUE TITLE
Project 1, Task 15

### ISSUE THREAD

**Issue by shihwachang** [ccsf-math-108/materials-fa23#15]
The task asked us to provide the poverty data on the "latest" year that is available and we were given the prompt of a FIRST function. If you use the FIRST function without modification, it would actually give you the first data( item (0), and eventually FAIL you at the auto check. So I modified the FIRST function to item (-1) and change its name to a LATEST function. That seems to make me pass the Otter. So I think the prompt is great in making me think how .group table function work, but you need to be careful NOT to use the FIRST function provided.

**Comment by shawnwiggins** [comment]
Thanks for sharing, @shihwachang. I'm not understanding if you are reporting an issue with the project notebook. I see that you are providing people with advice on how you think the task could be completed to pass the public auto-grader.

**Is there something specific that I can fix?**

**Comment by shihwachang** [comment]
Hello Sorry Professor I thought the First Function is really cool but I was certainly led into a wrong answer by using it. It indeed brightened me of thinking about (-1), though. I figured some fellow students may also encounter the problem. But if you think it’s good by learning how to dig yourself out of the hole would strengthen our learning experience then Thank you and we can certainly leave it at that.On Sep 27, 2023, at 9:22 AM, Shawn Wiggins ***@***.***> wrote:﻿
Thanks for sharing, @shihwachang. I'm not understanding if you are reporting an issue with the project notebook. I see that you are providing people with advice on how you think the task could be completed to pass the public auto-grader.
Is there something specific that I can fix?
