### ISSUE TITLE
Project 1, task 21

### ISSUE THREAD

**Issue by shihwachang** [ccsf-math-108/materials-fa23#16]
I am slightly confused about the first markdown cell of the task. We were only asked to write the codes in task 21, as the concept of writing it is being addressed in task 20. On the second cell of the task 21, we were given the cell with prompts to write the multiple line of codes( BTW for me this is the hardest question of the project 1), followed by a cell with a test run of 4 countries. I suggest to delete the first cell, unless I am confused about something else other than the codes that I need to address? BTW, in that cell I suggested to delete, I put down " please see the following cell for my codes" LOL!

**Comment by shawnwiggins** [comment]
Thank you for letting me know about the extra Markdown cell. I'll delete it for others.

@shihwachang, since you edited that cell, I don't think I have the ability to delete yours since the links preserve student work on cells.
