### ISSUE TITLE
Lab 05: Task 08: Grader Check: "2 Message" Spelling Typos (Very Minor)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#17]
In Lab 05, Task 08, the grader check "2 message" has the following spelling typos:

It reads as "Nice! You don't have the dolloar amoutn in millions of dollars." The words "dolloar amoutn" should be "dollar amount".

**Comment by shawnwiggins** [comment]
# Steps

- [ ] Update wording
- [ ] Rebuild Notebooks
