### ISSUE TITLE
Lab 05: Task 14: Preamble: Multi-Column group Method Call Example Typo (Moderate)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#18]
In Lab 04, just before Task 14 where it discusses how to group by more than one column, the example call structure shown reads as "The format would be tbl.group('Label 1', 'Label 2'], collect)". The example structure is missing the opening square bracket '[' for the list of columns, 'Label 1' and 'Label 2', on which to group by.

**Comment by shawnwiggins** [comment]
# Steps
- [ ] Add bracket
- [ ]  Rebuild Notebooks
