### ISSUE TITLE
Homework 05: Task 08: "End Question" Markup Block Typo (Minor)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#19]
In Homework 05, immediately after Task 08 in the markup block that is process delimited by "End Question", the second paragraph has a superfluous word "strings" in the first sentence right after the comma, which presently reads as "Before you go on to the next task, **strings** run the following code cell ..."

**Comment by shawnwiggins** [comment]
# Steps

- [ ] Remove extra word
- [ ] Rebuild notebooks
