### ISSUE TITLE
hw02 Task 18 Typo

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#2]
At the end of the sentence below the hint, it reads as "should be \$ |207 - 180| = " and then at tend of that task introduction after the period marking the end of the tip, it has "27$". I'm surmising that the "27\$" should be put with the "should be \$ |207 - 180|" to read "\$ |207 - 180| = 27$" maybe without the dollar signs showing up as they are likely formatting symbols for LaTeX math mode presentation.

**Comment by shawnwiggins** [comment]
Replace:

> For example, since the first three waiting times are 79, 54, and 74, the total waiting time for 3 eruptions is 79 + 54 + 74 = 207. The expected waiting time for 3 eruptions is 60 * 3 = 180. Therefore, `abs_diff_from_expected.item(2)` should be $|207 - 180| = 
> 
> **Tip**: We included some extra variables to help you break up this task into smaller pieces. We are only checking the `abs_diff_from_expected`, so you can remove any other variables that you don't want to use.27$.

with 

> For example, since the first three waiting times are 79, 54, and 74, the total waiting time for 3 eruptions is $79 + 54 + 74 = 207$. The expected waiting time for 3 eruptions is $60 * 3 = 180$. Therefore, `abs_diff_from_expected.item(2)` should be $|207 - 1 0| = 27$. 
> 
> **Tip**: We included some extra variables to help you break up this task into smaller pieces. We are only checking the `abs_diff_from_expected`, so you can remove any other variables that you don't want to use.

**Comment by shawnwiggins** [comment]
- [ ] Update text
- [ ] Rebuild notebooks
- [ ] Redistribute to staff repo for review
- [ ] Redistribute to students
- [ ] Message students about update

**Comment by shawnwiggins** [comment]
The text is now updated! If you re-open the notebook from the link in Canvas, then the updated text should be there.
