### ISSUE TITLE
Homework 05 Task 10

### ISSUE THREAD

**Issue by shawnwiggins** [ccsf-math-108/materials-fa23#20]
On task 10, there is a note:

> Don't worry there is only one winner, so you don't need to worry about ties.

This is a lie. There are ties. 😅

Continue working on the task as if there were no ties.

**Comment by shawnwiggins** [comment]
I'll update the task to include answers to the original question but have the task rephrased to create a table with each department and the length of the longest job name for each department.

# Steps

- [ ] Update phrasing of Task 10
- [ ] Rebuild notebooks

**Comment by shawnwiggins** [comment]
The grader will accept solutions to the new/current version of task_10 or the previous version of task_10.

**I'll leave this open for reference until the hw05 deadline.**

**Comment by asheynis** [comment]
In this new version, the task says to create a table called "departments", but the setup code given has the table named as "department", which also happens to be the same name as one of the desired columns.

**Comment by shawnwiggins** [comment]
@asheynis, good observation. The old solution had you give a string for a single department and use the name `department`. The new solution has you present the table of departments and uses the name `departments`. I changed the name to help with checking the old solution for those who submitted before the change was made.

I realize now after reading your comment that anyone who started Task 10 before the change was made will have `department` in the template, instead of `departments`.  I cannot change this based on the priority of preserving student work. In reflection, I probably just could have left the name the same to account for this situation. We will just need to pay extra attention to Task 10 when scoring it.
