### ISSUE TITLE
Project 01: Task 02: Code Repeated Twice & Done for Us (Moderate)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#22]
In Project 01, Task 02, the block of the code in which we have to create the initial and changed arrays has code for that task repeated twice with the second iteration completing the task for us. Is the second iteration with the solution the teacher's solution test code to check the execution that was left over in the final release?

**Comment by shawnwiggins** [comment]
# Steps

- [ ] Remove solution test.
- [ ] Rebuild notebooks.
