### ISSUE TITLE
Project 1: Task 05: Function description reference discrepancy (Minor/Moderate)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#24]
In Project 1, for Task 05, the description of the function before the code block says that it should take in two arguments of which the first is supposed to be named "country_code", however in the code block the function signature has the first argument named as "country". It may not matter, but in case the grading tool checks for names in the signature and body of the function, then it would be a problem.

**Comment by shawnwiggins** [comment]
# Steps

- [ ] Chance `country_code` to `country` in the description. 
- [ ] Rebuild the notebooks.
