### ISSUE TITLE
Project 1: Task 09, 11, 12_Pop_for_Year: Grader Check Execution Left in Notebook (Minor/Moderate)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#26]
In Project 1, Task 09, 11, and 12_Pop_for_Year have had the grader check executed with the output of the check left in the notebook. This might be an issue only on my end, but I have not attempted any of those tasks nor executed their grader checks. I an also attest that I did not accidentally run "Run Selected Cell and All Below" because the tasks afterward do not have their grader checks executed. I figure that those grader check message blocks will go away and be replaced once executed after the respective tasks are correctly completed, but I'm surmising that the raw notebook was not intended to have those grader check executions displayed for the students as it might either make them think that they did something wrong, messed up the notebook, or generally confuse them (all three of those scenarios played through my own mind when I first saw them). Is it possible that there was some test execution run during the (re)building of the notebook that executed those grader checks and then the notebook was saved before being release into production?

**Comment by shawnwiggins** [comment]
Thank you for the post, @asheynis. You can see in [the template version of the project in this repository](https://github.com/ccsf-math-108/materials-fa23/blob/main/project/project1/project1.ipynb) that none of the grader checks have been executed. So, I'm not sure what happened in your specific case, but I don't see what to fix.  In response to your question, before the notebooks are distributed to this repository, the script clears all the output of the notebook to get it in its final version which I linked above.

**Comment by asheynis** [comment]
Hi Shawn,

Thank you for sharing that with me. I am then confused myself, but I'm glad
to know it's just on my end and that it should all go away.

Alexander
