### ISSUE TITLE
Homework 06: Task 01: Function Description Typo (Minor)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#28]
In Homework 06, Task 01, the description of what the function should take as arguments reads with the typo "over time" when it should be "overtime" at the end of the second sentence.

**Comment by shawnwiggins** [comment]
# Steps
- [ ] Fix the mentioned typo in the function docstring.
- [ ] Fix the typo of `overt time` in the description.
- [ ] Rebuild the notebook
