### ISSUE TITLE
Homework 06: After Task 02: tbl.row(n) Comment Error (Moderate)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#29]
In Homework 06, just after Task 02, a markup block reminds us how to get specific rows from a table using tbl.row(n), however it says that it will get the _n_th row of the table but it should say (_n_+1)th row since Python uses 0 indexing for all iterables. For example, the code block afterward that we have to execute as is uses games.row(10), returning the row with the opponent being Sequoia which is the 11th row of the (football) games table.

**Comment by shawnwiggins** [comment]
Good point!

# Steps

- [ ] Change `n`-th to `(n+1)`th.
- [ ] Rebuild notebook
