### ISSUE TITLE
Homework 06: Task 04: Column Name Not Specified for Column with results Array (Minor/Moderate)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#30]
In Homework 06, for Task 04, we are told to add a column containing the results of CCSF's football games to the final_scores table, however we are not told what to name that column. The grader check does not validate that column name, so this might not be an issue, but there is a chance students might worry that a hidden test might check for the column name. Also, the question is whether it is intended that each students' homework should have the same names for all final objects that are being graded. I used the column name "Result" as it was the most natural one based on the array name.

**Comment by shawnwiggins** [comment]
I do want to make sure the expectations mentioned mirror the (hidden and public) tests performed, so thanks for bringing this up. The column names are not being checked, so I'll mark this as not an issue.

**Comment by asheynis** [comment]
You're welcome! Honestly, reporting the bugs at least the more
grade-oriented ones is all helping me out because I wonder if I might get
dinged on some subtle oversight and that would be annoying!
