### ISSUE TITLE
Homework 06: Comparing Choices Section Question Count Incorrect (Minor/Moderate)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#31]
In Homework 06, for the last section titled "Comparing Choices", you mention that students should enter a numerical value associated to an outcome relating event A and event B, but there are only two questions/tasks (Task 11 and Task 12) that are in that section. I'm guessing that either there are third question which was later removed or a third question that was supposed to be included but accidentally omitted in producing this homework.

**Comment by shawnwiggins** [comment]
Good observation. A 3rd task was removed from the Berkeley assignment. I'll update that language.

# Steps

- [ ] Update wording
- [ ] Rebuild notebook
