### ISSUE TITLE
HW06 Before task 07

### ISSUE THREAD

**Issue by shihwachang** [ccsf-math-108/materials-fa23#32]
I don't see a table named Wheel, although I can imagine 1 column has 0,00, 1....36, the other has colors associated (G, B, R.....) with it.

**Comment by shihwachang** [comment]
As I continue to work thru task 7-12, I could get the answer by using Python as a calculator without using the Wheel table and num_row Table_method. Is that what we are expected to do? No complicated programming involved?

**Comment by shawnwiggins** [comment]
Thank you for reporting this, @shihwachang. I needed to span the roulette exercises over two homework assignments this semester. It seems that I failed to set up the table for you in hw06. I'll do that now.

# Steps
- [ ] Add `wheel` table
- [ ] Rebuild notebooks
