### ISSUE TITLE
Lab06 multiple issues

### ISSUE THREAD

**Issue by shihwachang** [ccsf-math-108/materials-fa23#33]
1. We are not able to submit Lab06_html( no button for it), likely due to the extension of the deadline, then subsequently Canvas considered 'late" for everyone.
2. . Task 06 and 07, since you didn't strip the punctuation marks, it would be nice to add a notation "that 5 letter word means 5 characters in a string, therefore 'pride!' is a 6 character word, rather than a 5 character word"
3. task 08, we have to assume that she is "blindly" throwing a dart and each throw lands on the dartboard and the chance of hitting each score is "equal", since in the real dart game, you want to hit a "10 "rather a "1", therefore the chance of hitting 10 is different from the chance of hitting 1.

**Comment by shihwachang** [comment]
Hi I was able to submit Lab06 as of Sunday morning.

**Comment by shawnwiggins** [comment]
1. It sounds like you were logged out of Canvas if you were not able to see a submit button. I'm glad you were able to resolve that.
2. Thank you for the suggestion. I can add a clarifying note.
3. I'm not following your question/issue that you are reporting for task 08.

**Comment by shawnwiggins** [comment]
After talking more, it seems that this is a good comment for modeling a real-life dart game, but this task reflects a very simplified situation.

**Comment by shawnwiggins** [comment]
# Steps

- [ ] Add clarification to task_06
- [ ] Rebuild notebooks
