### ISSUE TITLE
Project 1: Task 22: Typo in First Sentence of Task Description (Minor)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#34]
In Project 1, Task 22, the opening sentence of the task description reads as "The graphic for India shows **a A**ccording to the data,..." Based on my understanding of what the intended sentence should read as, the bolded upper case 'A' and the space between it and the lower case 'a' should be deleted, so that it reads as "The graphic for India shows according to the data, ..."

**Comment by shawnwiggins** [comment]
I'll Replace

> The graphic for India shows a According to the data, the number of people living in extreme poverty has been increasing in Nigeria and the United States, the massive decreases in China and India have shaped the overall trend that extreme poverty is decreasing worldwide, both in percentage and in absolute number. 

with 

> According to the data, the number of people living in extreme poverty has been increasing in Nigeria and the United States, and the massive decreases in China and India have shaped the overall trend that extreme poverty is decreasing worldwide, both in percentage and in absolute number. 

# Steps

- [ ] Make the change
- [ ] Rebuild the notebooks
