### ISSUE TITLE
Exam Practice: Midterm Exam: Instruction 1 Typo (Minor)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#36]
In the module page for Exam Practice: Midterm Exam, the first instruction has a parenthetical inclusion that reads as "(There is a download button **int he** top right corner of the document preview in GitHub.)" The typo is highlighted in bold and should read as "in the".

**Comment by shawnwiggins** [comment]
# Steps

- [ ] Edit page
