### ISSUE TITLE
HW3 Task 3 Grader Output Typo

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#4]
For the HW3 Task 3 grader output when you get a seemingly correct answer, it outputs, "There are 10 rows (quarters)**b** in your table." The bolded letter 'b' seems like a typo as it serves no syntactical nor spelling function. A very, very minor issue, but I thought it would be worth reporting.

**Comment by shawnwiggins** [comment]
Thanks @asheynis. I'll update that as soon as possible for the others. It is a minor error, so I won't announce it, but I do appreciate your attention to detail and support in cleaning up the presentation of these assignments.

**Comment by shawnwiggins** [comment]
# Steps
- [ ] Edit the auto-grader feedback.
- [ ] Rebuild the notebooks.
- [ ] Push the notebooks to the staff and student repositories

**Comment by asheynis** [comment]
Hi Shawn,

That makes sense. Catching these and general reading errors is more of a
personal assessment of how much attention I'm paying to the content and
thinking about what I am reading in contrast to what I know.

Thanks!

Alexander
