### ISSUE TITLE
HW10: Task 04: Formula for Imm Thai's Lead Is Confusing (Moderate)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#51]
In Homework 10, Task 04, the descriptive formula given for calculating Imm Thai's lead over the totality of the other restaurants uses two different phrases that seem so similar, "Imm Thai's percent of the vote" and then "Imm Thai's percent of Vote" and are not phrased in a way that delineates whether they are the same value or if one comes from the original sample. Logically, it would make sense for it to be the same value so as to track each resamples lead for Imm Thai, but the different wording does beg the question.

**Comment by shawnwiggins** [comment]
I'll update the formula to indicate that they are the same.
