### ISSUE TITLE
HW10: Task 01: Phrasing of Function Unclear (Moderate)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#52]
In Homework 10, Task 01, we are instructed to write a function that will compute "Imm Thai's percentage of votes after simulating one bootstrap sample of tbl." Is it saying that tbl is already a resample of the votes table? Or is it saying that we need to resample the votes table and then do the percentage calculation? I only bring this up because in Task 04, given how the skeleton of the function is setup, it suggests that tbl in Task 01 is resample of votes, but I just want to be sure.

**Comment by shawnwiggins** [comment]
Good question/point. `tbl` is the sample data. This means you need to create a bootstrap resample from the sample data in `tbl`. I suppose, in theory, `tbl` is a possible resample. It is unlikely that a resample will be exactly the same as the original sample though.

In Task 04, the phrase "from one bootstrap sample of `tbl`" is suggesting that `tbl` is the original sample and you need to work with a resample from that data. 

I'll add a clarifying note to Task 01.

**Comment by asheynis** [comment]
I only just got around to reading the clarification. I only just got around to reading your clarification and I think I did Task 01 incorrectly. Just to be clear (and I apologize if I am being pedantic, but by "[t]his means you need to create a bootstrap resample from the sample data in tbl," do you mean that when we write the function one_resampled_percentage, inside that function we have to do a resample of tbl and then return the percentage that results from that?

If so, then in Task 04, the presence of the bootstrap variable throws me off because if bootstrap is already a resample of the original sample in tbl, then passing that resample into the earlier function from Task 01, one_resample_percentage, based on how I am now understanding that function to work, we would be resampling from an already resample table, which while it still accomplishes the goal (and is random), seems odd.

My Task 01, one_resample_percentage function does not resample tbl but just computes the percentage. It expects the input table to be resampled already.

**Comment by shawnwiggins** [comment]
A `bootstrap` variable would be in both functions.

**Comment by asheynis** [comment]
Then that still raises the question of why a bootstrap would need to be in both functions as it really only needs to be in the percentages function since the differences function would call the percentages function which already does a resampling of the original table inside of it. I think that is what was still puzzling me.

**Comment by shawnwiggins** [comment]
Good point. Looking at their template/instructions:

* Task 01: This function creates a bootstrap resample, calculates the percentage, and returns the percentage. This gives a simulated test statistic value based on a resample.
* Task 04: This function creates a bootstrap resample, calculates the percentage, and returns the difference. 

After looking at this setup further based on your raised issue. I agree that it is unnecessary to get the resample in the Task 04 function. Simply calling the function from Task 01 in the function for Task 04 would get the resample and calculate the percentage. From there you can just use the provided formula. For example:

``` python
def one_resampled_difference(tbl):
    imm_percentage = one_resampled_percentage(tbl)
    return  imm_percentage - (100 - imm_percentage)
```

I'll make a note that we should consider updating the template/phrasing of this for future semesters if this assignment will continue to be used.
