### ISSUE TITLE
Project 2: Task 2.04: Wording of Prompt Misleading and Typo (Moderate)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#53]
In Project 2, Task 2.04, the wording of the prompt says "to choose a test statistic based on our alternative hypothesis in Task **2.2**." The reference to Task 2.2 should be Task 2.02. As for the phrasing, is our selection supposed to be based on how we phrased our Alternative Hypothesis? From the lectures and discussions in class, from the perspective of the researchers and how the whole situation has been presented to us, there is one natural/consistent choice for the Alternative Hypothesis and thus the corresponding statistic. However, it can be argued that an equivalent statistic could be chosen that gives a computation reflect a different phrasing of the Alternative Hypothesis that is equivalent. So, should we pick all the options that _could_ be valid based on _any_ valid Alternative Hypothesis? Or should we make the choice based on our own phrasing?

**Comment by shawnwiggins** [comment]
Thanks for pointing out the task reference typo. I'll update that now.

There are a variety of ways to phrase an alternative hypothesis. The alternative should reflect "bigger than", "less than", or "not equal to". With the correct $>$, $<$, $\neq$ phrasing for the alternative hypothesis, there could be an infinite number of valid ways to create a test statistic (measurement) that could be used to provide evidence against the null hypothesis and for the alternative hypotheses. For this task, there should be a collection of test statistics that would work to support any variation of the correct $>$, $<$, $\neq$ phrasing of the alternative. 

@asheynis, does this address your issue? 

@amclanahan, do you have anything to add to or correct in what I wrote?

**Comment by asheynis** [comment]
Yes, this addresses my concern. It was more the semantics of "our" or "your" choice of null hypothesis and alternate hypothesis being the means by which one has to pick which of the statistic(s) is one that would work as a way of testing the hypotheses. I suppose if it was phrased as "which of the statistics below could be used to test a valid null and alternative hypothesis" independent of our personal phrasing of the hypotheses, then it would be clearer at least to me. Perhaps to others, there was no confusion, but I just thought I would bring it up. Thank you!

**Comment by shawnwiggins** [comment]
@asheynis, thanks for being direct with that. I missed the "our"/"your" point.
