### ISSUE TITLE
Lecture 33 Video: Last Example: predict Function body Error for intercept Variable (Moderate/High)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#55]
In the Lecture 33 video, for the last example where we code up the body of the predict function, you code the calculation of the intercept variable as "intercept = mean_**X** - slope * mean_X". The bolded "X" should be "Y".

**Comment by shawnwiggins** [comment]
Good catch, @asheynis. I added the following note to the Loom video description/summary:

> Update: The code for the intercept at 17:20 is incorrect. It should be mean_Y - slope * mean_X.

I'll leave this issue open until next week for those who still need to go through the video.
