### ISSUE TITLE
Week 04: Lecture 09: [Optional] Interactive Charts with Plotly: Typo in Bullet Point #3

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#6]
A very minor typo in the Week 04, Lecture 09 optional topic "Interactive Charts with Plotly". The third bullet point states that "The arguments change to fight the Plotly functions," but I think that the word "fight" should be "fit".

**Comment by shawnwiggins** [comment]
# Steps

- [ ] Change "fight" to "fit" in notebooks.
- [ ] Push notebooks to staff and student repositories.
