### ISSUE TITLE
Project 3: Task 1.1.3: Opening Question Phrased Strangely (Moderate)

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#61]
In Project 3, for Task 1.1.3, the opening question reads as "What is the longest word in the dataset whose stem wasn't shortened?" but seeing as the stem by definition is the shortest reduction to which a word can be mapped, then it would make more sense to ask "What is the longest word in the dataset that wasn't shortened to its stem?"

**Comment by shawnwiggins** [comment]
Good point. The stems are not shortened, the words are shortened to the stem or are equal in length to the stem.
