### ISSUE TITLE
Lecture 40: Slide Page 11 ("Save you Files Before End of December": Typo & Broken Link

### ISSUE THREAD

**Issue by asheynis** [ccsf-math-108/materials-fa23#70]
The title should be fixed to "Save Your Files before End of December" (I think for longer prepositions there is some debate as to whether the first letter should be capitalized but I tend to adhere to keeping all prepositions lower cased).

The link to the CCSF cloud bank seems to be broken.

**Comment by shawnwiggins** [comment]
I used your sugged title and fixed the link. Thank you.

**Comment by asheynis** [comment]
Oh, just saw this comment after I responded to your e-mail. Glad I could help! Thank you for the quick fix!
